### PR TITLE
Fix: copy recursively from read only location. (fixes #98)

### LINKED ISSUE #98: cp does not recursively copy from readonly location
shell.cp('-R', <src readonly> , dest) fails with the following error:

cp: copyFileSync: could not write to dest file (code=EACCES): <dest>

### PR DESCRIPTION
**Pull request by Fransz**
I think this fixes #98 
Tested on OS X, but not on windows/linux.

A test was added.

### CODE REVIEW

**Comment by nfischer** [comment]
@Fransz thanks so much for the PR! Can you investigate the windows failure? This may be due to chmod not working correctly on Windows. If so, feel free to skip the tests on Windows.

 Can you rewrite the tests to not modify `resources`? Copy the files out first, then modify them, and then do a copy to test that read-only works.

Can you please add a test for an individual read-only file as well?

**Comment by Fransz** [comment]
Tests are adjusted, and skipped on windows as asked by @nfischer 

I'm not sure to change the file permissions on the copied directories/files. 
The -p flag should be used for that really.

**Comment by nfischer** [comment]
@Fransz can you also verify that the permissions are still correct after copying? This should do the trick:

```js
assert.equal(fs.statSync('tmp/cp_cp').mode & parseInt('777', 8), parseInt('555', 8));
```

**Comment by Fransz** [comment]
I've added assertions for the permissions being correct after copying as @nfischer requested.
This doesn't pass travis however;

The test fails on a single job (not the complete travis build);
Repeating the build fails again, but now on a different job (i.e. different node version);

I've tried several times. The only thing in common seems to be that all failures happend on OS X jobs.

I'm new to travis, so i really do not know how to fix this.

**Comment by nfischer** [comment]
@Fransz I'll look into Travis. Sounds like flakiness, either in the test or in Travis. I'll ping this if there's any action we need from you. Thanks for pointing it out!

**Comment by nfischer** [comment]
To me, this doesn't look like a bug that is due to Travis. I can't reproduce it locally though, so I restarted the whole build. If it passes with no failures, we can merge now and fix it the next time the failure arises. Otherwise we'll investigate further.

I may mark the test with a TODO to examine the flakes later.

**Comment by nfischer** [comment]
Just restarted the test again. Since it seems like the test keeps flaking, @Fransz would you mind redoing the tests after #565 is merged? Using a real framework may help with test reliability.

**Comment by Fransz** [comment]
@nfischer, i rewrote the tests in ava. 
Unfortunately this doesn't seem to help. Tests keeps failing in an unpredicatable way.

**Comment by nfischer** [comment]
@Fransz thanks for doing the refactor. It looks like other tests in `cp` are flaking now. Those flakes are probably due to our refactor to ava.

I'm going to see if I can resolve the general flakiness, and then I'll try to merge PR in.

**Comment by nfischer** [comment]
Bumping this back to v0.8, since we're focusing efforts there.

**Comment by nfischer** [comment]
Bumping to v0.9 milestone

**Comment by nfischer** [comment]
Unfortunately, this has sat unmerged for a long time. Looking at the code, this doesn't seem to be too hard to cherry pick to a new branch. I'll try this out.

**Comment by nfischer** [comment]
Close in favor of #870. Thanks for this fix!

**Pull request closed without merging**
