### PR TITLE
Added -L follow sym link option to cp

### PR DESCRIPTION
**Pull request by charlesverge**
Added option to allow cp to follow sym links and copy source files rather than sym link.

### CODE REVIEW

**Comment by ariporad** [comment]
@charlesverg: Thanks so much for your PR! Could you please add some tests? Thanks!

**Comment by nfischer** [comment]
:+1:

**Comment by nfischer** [comment]
@charlesverge could you also rebase off of master? We now have Windows tests. Thanks!

**Comment by ariporad** [comment]
@charlesverge: Hi! Would you mind rebasing this off master? We'd like to get it in v0.7.0! Thanks!

**Comment by nfischer** [comment]
@charlesverge any further work on this? If not, either @ariporad or I can take this PR over.

**Comment by ariporad** [comment]
@nfischer: I think one of us should take this over, do you want it, or should I?

**Comment by nfischer** [comment]
@ariporad you can take this one if you like

**Comment by nfischer** [comment]
Also, @ariporad, you might be able to also resolve #193 while you're at it, since that's related to `cp` and symlinks

**Comment by ariporad** [comment]
@nfischer: #193 kind of breaks my head, I really don't get it.

**Comment by nfischer** [comment]
@ariporad I might be able to take a look. I just have a lot on my plate right now, so I've been focusing on some other things. There are a couple other shelljs features that are higher up on the priority list for me.

**Comment by ariporad** [comment]
@nfischer: I'll actually take this on.

**Comment by nfischer** [comment]
@ariporad Are you still taking this on? This would be a nice feature for v0.7, but it might also be hard to get Windows compatibility.

**Comment by ariporad** [comment]
@nfischer: I'll try. I'm not great at Windows, but I'll try.

**Comment by charlesverge** [comment]
@nfischer @ariporad 

I've pushed a new commit that is based off the lasted master branch it includes

1. A maxdepth option to prevent run away recursion
2. A check for a link cycle where a link refers to a directory with in the directory being copied
3. Unit tests for the -L option and maxdepth

I've executed these tests on a windows 7 machine and they pass successfully.

https://github.com/shelljs/shelljs/pull/232/commits/0c3f8cb995bd2f1e079c78464d46454bb7f0b39c

**Comment by charlesverge** [comment]
If the goal is to duplicate native behavior

On a macbook and Linux/Ubuntu a native cp -RL does no copy cycling links and copies non cycling links as directories rather than sym links.

On Windows 7 the xcopy command line gives an insufficient error for a cycling link and for the non cycling link it copies the directory structure as if it is not a link. Using the file manager results in the link being a blank directory.

**Comment by charlesverge** [comment]
Also any hints on why the travis-ci build fails would be cool.

**Comment by ariporad** [comment]
@charlesverge: It looks like you've changed the docs for cp in the docstring [here](https://github.com/shelljs/shelljs/pull/232/files#diff-be2413c6f24044cccb6e7703f4635b85R137), but you haven't regenerated the docs. You can do this with `node scripts/generate-docs`.

**Comment by charlesverge** [comment]
@ariporad Looks like that was it.

**Comment by nfischer** [comment]
@charlesverge thanks for the PR! Looks pretty good. If I have any questions, I'll ping this thread

**Pull request closed without merging**
