### PR TITLE
ci: test Node.js 6, 8, 10 and 11

### PR DESCRIPTION
**Pull request by DanielRuf**
Test only Node.js 6, 8, 10 (LTS) and stable (11).

https://github.com/nodejs/Release/blob/master/README.md

### CODE REVIEW

**Comment by nfischer** [comment]
- For dropping v4/v5, see #873
- v10 has a bug right now (#856) (help would be appreciated)
- We probably *won't* drop v7/v9
- We can't use `npm install`, we have our own script (see #896)
- We chose `c++` as a language a long time ago, and I can't remember why (so I can't tell you if the reason is still relevant). I think it was just to get finer-grained control over our CI steps

**Comment by DanielRuf** [comment]
> We probably won't drop v7/v9

But why? They reached their EOL.

**Comment by DanielRuf** [comment]
> We can't use npm install, we have our own script (see #896)

This produces different results in CI and production (lockfiles are not working there).

> We chose c++ as a language a long time ago, and I can't remember why (so I can't tell you if the reason is still relevant). I think it was just to get finer-grained control over our CI steps

But it does not seem to be used.
I'll check and update the CI script.

**Comment by DanielRuf** [comment]
> Not sure I quite understand. Are you objecting to the use of lockfiles in general, or objecting to our install wrapper?

The first, this is why `npm ci` is a bit dangerous (works in our CI - but not in production).

**Comment by DanielRuf** [comment]
Probably, or use `npm install` on CI.
At least CI often produces a different dependency tree than the installed package in production as it is often a child dependency of another dependency and below the root lockfile it is only locked to the SemVer range in the package.json files (or better: pinned there to a specific version).

Not yet sure what the best solution for everyone is. It's a bit inconsistent across platforms (dev, prod, CI), tools (yarn, npm version) and repository settings (a lockfile might be useful for contributors and CI to build reproducible builds but many big devs like Sindre and others do not use lockfiles for such reasons afaik).

Also see https://github.com/sindresorhus/ama/issues/479

**Comment by nfischer** [comment]
Replaced by #910, #917, and #921

**Pull request closed without merging**
