### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by deining**
This PR fixes a few typos that I spotted in the project. I will sign my commit soon.

### CODE REVIEW

**Comment by deining** [comment]
The commit is signed now.

**Review by nfischer — APPROVED** [review]
Thank you, this is awesome!

**Comment by nfischer** [comment]
Can you please rebase on top of the latest `master` branch? I made some changes today to fix up the tester bots.

**Comment by deining** [comment]
> Can you please rebase on top of the latest `master` branch?

Done.

**Pull request merged**
