### PR TITLE
Chore drop 0.12

### LINKED ISSUE #647: Drop support for v0.12
According to the [NodeJS LTS schedule](https://github.com/nodejs/LTS), v0.12 support was dropped by Node in December 2016. This means it's probably reasonable to drop the support in our v0.8 release.

This has some benefits for us:

 - we can cut v0.11 and v0.12 from our Travis builds for faster CI (maybe even iojs too, which sometimes has false negatives)
 - we can significantly trim down on the code inside `src/exec.js` (there's a whole [v0.10-specific else-branch](https://github.com/shelljs/shelljs/blob/4c48631d745ef4cb3e9d198b37e5772fb57ce905/src/exec.js#L128))
 - we can [clean up tests](https://github.com/shelljs/shelljs/blob/4c48631d745ef4cb3e9d198b37e5772fb57ce905/test/exec.js#L116)
 - we can trim down `src/tempdir.js` a [bit as well](https://github.com/shelljs/shelljs/blob/4c48631d745ef4cb3e9d198b37e5772fb57ce905/src/tempdir.js#L43)
 - we can remove our `Object.assign()` polyfill (if we remove iojs as well)

@freitagbr what are your thoughts on dropping v0.12 support? What about dropping iojs support? We'll get the biggest CI benefits if we go with iojs, but I don't know if many people still rely on it (my guess is iojs users have moved on to v4+).

### PR DESCRIPTION
**Pull request by nfischer**
Fixes #647

### CODE REVIEW

**Comment by nfischer** [comment]
@freitagbr I updated the README to mention v4+. I don't think it's necessary to mention this corresponds with v0.8, since that'll be the version once we merge dev into master.

**Comment by nfischer** [comment]
And yes, dev branch contains changes for v0.8. Once we get close to a release, we can merge into master and do the finishing touches on the master branch. Postponing the merge is helpful, otherwise v0.8 docs will show up on the README before it's released.

**Comment by freitagbr** [comment]
CI passed, so LGTM.

**Comment by freitagbr** [comment]
LGTM, needs a rebase off of `dev` though.

**Comment by nfischer** [comment]
Updated with Github UI. Should be fine, since it all squashes anyway.

**Pull request merged**
