### PR TITLE
Release v0.7.0

### LINKED ISSUE #376: Copy not accepting wildcards + file ending anymore when using -r
So while `ls("src/*.html")` returns an array of html files, `copy("-r", "src/*.html", "dist")` results in an error. It works without -r.
I'm on Windows 7 x64, Node 5.7, using 0.6.

### PR DESCRIPTION
**Pull request by nfischer**
Changelog from v0.6.0...v0.7.0:

### Bug Fixes

* fix: null is no longer confused for an object
* fix(ls): no trailing newline for empty directories (#425)
* fix: error message now printed for fatal failures
* refactor(cp): clean up code and fix #376
* Perf improvement for ls, and fix for Windows
* Improved cd performance and fix error messages
* fix(exec): properly handles paths with spaces and quotes
* fix(verbose): verbose-style logging is consistent
* fix(exec): now actually supports shell option
* fix(exec): temp files are now cleaned up

### Features

* feat(cp): -P option, plus better handling of symlinks (#421)
* feat(command): new command: tail()
* feat(command): new command: head()
* feat(command): new command: sort()
* feat(glob): expose config.globOptions.
* feat(cp): add -L/follow symlink option
* feat: adding error codes to ShellJS
* feat(pipe): add support for pipes between commands
* feat(touch): supports multiple files
* feat(set): add -f option to disable shell globbing
* feat(glob): use glob module for globbing
* feat(glob): glob support for (almost) all commands
* feat(grep): add -l option

### CODE REVIEW

**Comment by nfischer** [comment]
@ariporad

Feel free to modify the changelog as you see fit (I just generated it from `git log` commands). It's not quite as fancy as the one from the last release, but it's good enough for my tastes so I didn't bother with extra formatting.

Also, let me know if you want to remove Artur from package.json (he mentioned in an email thread that this would be fine, but I don't think it matters much either way).

**Comment by ariporad** [comment]
LGTM, thanks so much for all your hard work on this. Sorry I haven't helped more.
I personally feel like it's ok to remove him (mainly so people don't contact him by mistake).

Thanks! Ari
On Sun, Apr 24, 2016 at 5:11 PM, Nate Fischer <notifications@github.com> wrote:
@ariporad [https://github.com/ariporad]

Feel free to modify the changelog as you see fit (I just generated it from git log commands). It's not quite as fancy as the one from the last release, but it's good enough for my tastes so I didn't bother with extra formatting.

Also, let me know if you want to remove Artur from package.json (he mentioned in an email thread that this would be fine, but I don't think it matters much either way).

**Comment by nfischer** [comment]
LGTM

**Comment by nfischer** [comment]
This is now available on npm :+1:

**Pull request merged**
