### PR TITLE
Release v0.6.0

### PR DESCRIPTION
**Pull request by ariporad**
v0.6.0! The first release by @ariporad and @nfischer!

Changelog from v0.5.3...v0.6.0:

<a name="0.6.0"></a>
### Bug Fixes

* **regexes:** make regexes more consistent with `sed` and `grep` ([1ee696d](https://github.com/shelljs/shelljs/commit/1ee696d))
* **cat:** make behavior more like unix ([580d6d3](https://github.com/shelljs/shelljs/commit/580d6d3))
* **cp:** add `-n` option, make `-f` default behavior ([8377b92](https://github.com/shelljs/shelljs/commit/8377b92))
* **mv:** add `-n` option, make `-f` default behavior ([2d1ee4d](https://github.com/shelljs/shelljs/commit/2d1ee4d))
* **windows:** fix `shjs` tests for windows ([985ac20](https://github.com/shelljs/shelljs/commit/985ac20))
* **windows:** fix symlinking on windows ([fb5a7ec](https://github.com/shelljs/shelljs/commit/fb5a7ec)), closes [#301](https://github.com/shelljs/shelljs/issues/301).
* **which:** properly search `PATHEXT` on Windows ([eaa7710](https://github.com/shelljs/shelljs/commit/eaa7710)), closes [#301](https://github.com/shelljs/shelljs/issues/301).
* **electron:** fix electron compatibility by not doing `console.log.apply(this, ...)` ([9e9b500](https://github.com/shelljs/shelljs/commit/9e9b500)), closes [#255](https://github.com/shelljs/shelljs/issues/255).

### Features

* **expand:** add tilde expansion to `expand()` ([b3f2664](https://github.com/shelljs/shelljs/commit/b3f2664))
* **cd:** `cd()` (no args) changes to home directory ([dfaa78a](https://github.com/shelljs/shelljs/commit/dfaa78a))
* **ls:** add `-d` flag to `ls()` ([c6da9e7](https://github.com/shelljs/shelljs/commit/c6da9e7))
* **ls:** add `-l`  option ([e918c75](https://github.com/shelljs/shelljs/commit/e918c75))
* **sed:** support multiple file names ([bccf620](https://github.com/shelljs/shelljs/commit/bccf620)), closes [#231](https://github.com/shelljs/shelljs/issues/231)
* **set:** add new `set()` command ([ca045ea](https://github.com/shelljs/shelljs/commit/ca045ea))
* **cd:** `cd('-')` now returns you to the previous directory, as in bash ([1979d07](https://github.com/shelljs/shelljs/commit/1979d07))
* **chmod:** add `X` for directories ([766c2dd](https://github.com/shelljs/shelljs/commit/766c2dd))
* **exec:** add `exec(...).stdout` ([8a7f7ce](https://github.com/shelljs/shelljs/commit/8a7f7ce))
* **exec:** allow passing options to `child_process.exec` ([c0d9cf7](https://github.com/shelljs/shelljs/commit/c0d9cf7))
* **options:** options with values (see `touch -r` for an example) ([f9c8fc0](https://github.com/shelljs/shelljs/commit/f9c8fc0))

### CODE REVIEW

**Comment by nfischer** [comment]
LGTM

**Comment by nfischer** [comment]
@ariporad Can we add @arturadib back as author?

**Comment by nfischer** [comment]
LGTM

**Comment by ariporad** [comment]
@nfischer: Can I get approval of the changelog too? Thx.

**Comment by nfischer** [comment]
@ariporad Changelog looks good as well :+1:

**Comment by nfischer** [comment]
Feel free to merge

**Comment by ariporad** [comment]
@shelljs/contributors: v0.6.0 RELEASED!!!

**Comment by nfischer** [comment]
Awesome! Excellent work!

**Pull request merged**
