### PR TITLE
ci: test on Linux, macOS and Windows

### PR DESCRIPTION
**Pull request by DanielRuf**
We can also use Windows on Travis CI now.

### CODE REVIEW

**Comment by DanielRuf** [comment]
I'm not entirely sure why `c++` is used in the config. So far Teavis CI is faster, has better support and supports all three big platforms. So one less CI config.

I'll check if we can easily switch to `node_js`.

**Comment by DanielRuf** [comment]
I'm not entirely sure why `c++` is used in the config. So far Travis CI is faster, has better support and supports all three big platforms. So one less CI config.

I'll check if we can easily switch to `node_js`.

**Comment by DanielRuf** [comment]
Flaky results with AppVeyor: https://ci.appveyor.com/project/shelljs/shelljs/builds/20638733/job/15ypqpfw6c1mxpuu

**Comment by nfischer** [comment]
@DanielRuf FYI I merged `master` into your branch to resolve conflicts. Let's see how our tests run on Windows Travis :smile:

**Comment by nfischer** [comment]
It seems we have modified files ([example run](https://travis-ci.org/shelljs/shelljs/jobs/462357890)). #918 might help narrow down where the issue lies.

**Pull request closed without merging**
