### PR TITLE
Small clarification of verbose flag

### PR DESCRIPTION
**Pull request by zommerfelds**
Hi, just though this might be useful for someone. I had to run a test manually to see if custom exec commands also show up as verbose.

### CODE REVIEW

**Comment by nfischer** [comment]
@zommerfelds thanks for the PR. After looking over this, maybe it would also be good to show a command with options. How about:

`rm('-rf', 'foo.txt', 'bar.txt');` :arrow_right: `rm -rf foo.txt bar.txt`

Maybe this could replace the `ls` example, since it doesn't add much to the `cd` example.

**Comment by zommerfelds** [comment]
@nfischer: Sorry for the delay on this one! I made your suggested changes.

**Comment by nfischer** [comment]
@zommerfelds Can you make the change in the corresponding source file? README docs are autogenerated. After you change that file, you can run `npm run gendocs`. Thanks!

Other than that, LGTM.

**Comment by zommerfelds** [comment]
Hi @nfischer. I hadn't noticed that this was auto generated. Just added the change to the source file and regenerated the Readme.

**Comment by nfischer** [comment]
Thanks!

**Pull request merged**
