### PR TITLE
Fix lint warning

### LINKED ISSUE #542: Lint warning
### Node version (or tell us if you're using electron or some other framework):
6.9.1
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.5
### Operating system:
OS X 10.11.6
### Description of the bug:
There's a lint warning on line 50 of `src/rm.js`
### Example ShellJS command to reproduce the error:

```
$ npm run lint

> shelljs@0.7.5 lint /Users/freitagb/src/javascript/shelljs
> eslint .

/Users/freitagb/shelljs/src/rm.js
  50:5  warning  Unexpected constant condition  no-constant-condition

✖ 1 problem (0 errors, 1 warning)
```

### PR DESCRIPTION
**Pull request by freitagbr**
Fixes #542

### CODE REVIEW

**Comment by nfischer** [comment]
@freitagbr Could you add a TODO for refactoring the infinite loop? We haven't received any bugs about it hanging, so we don't have to fix it right away, but it would be nice to eventually refactor so that we're confident it will never be a problem.

**Comment by freitagbr** [comment]
Ok, will do.

**Comment by nfischer** [comment]
LGTM. Feel free to merge when CI passes

**Comment by freitagbr** [comment]
I think you'll have to do that, I don't have write access.

**Pull request merged**
