### PR TITLE
Revert "refactor: replace fs.existsSync" fixes(#531)

### PR DESCRIPTION
**Pull request by gyandeeps**
This reverts commit ab8cf5a8e027b28fc7b784587e4339d2b6d0f08f.

### CODE REVIEW

**Comment by nfischer** [comment]
LGTM. Travis has been pretty unreliable lately, so if the remaining jobs don't start (they seem stuck), then we can merge without waiting.

**Comment by gyandeeps** [comment]
here is build for the same changes: https://travis-ci.org/shelljs/shelljs/builds/168346303
I u[date the commit message thats why build started again

**Comment by nfischer** [comment]
Ok great. Travis should be done pretty shortly for this update then

**Comment by nfischer** [comment]
Thanks again, @gyandeeps!

**Comment by nfischer** [comment]
Fixes #531

**Pull request merged**
