### PR TITLE
Added -n to cp

### PR DESCRIPTION
**Pull request by SerenadeX**

### CODE REVIEW

**Comment by SerenadeX** [comment]
The -n option allows the user to copy things from one directory to another without overwriting existing files in the destination

**Comment by arturadib** [comment]
hey there- sorry I'm late to this. mind modifying the test to actually check the file contents to ensure the file wasn't overwritten? thanks!

**Comment by nfischer** [comment]
@SerenadeX would you be able to address the comment above from @arturadib? If so, I'd be interested in merging!

Also, would you be able to rebase off master?

**Comment by nfischer** [comment]
@SerenadeX Thank you so much for the PR! I think we'll have to close this, however, since this is replaced by #336. Thanks for the idea!

**Pull request closed without merging**
