### PR TITLE
redux adding -l and -s support to grep. 

### PR DESCRIPTION
**Pull request by idearat**
Merged with the latest master and tested locally and on travis @ https://travis-ci.org/idearat/shelljs and everything passed cleanly. Hopefully we'll have better luck this time :).

### CODE REVIEW

**Comment by nfischer** [comment]
@idearat thanks for the PR! Would you be able to rebase off of master?

Also, what does `-s` add that `config.silent` doesn't? My concern is that `common.error()` isn't called if the `-s` flag is passed, so a `grep()` command that finds no results will technically succeed (based on checking with `shell.error()`), which differs from unix behavior.

**Comment by idearat** [comment]
@nfischer It's been a while since I authored this. I'll need to look back at it and take your comments re: common.error() into consideration. Will try to update within a day or two. And thanks for taking it under consideration!

**Comment by nfischer** [comment]
@idearat thanks! And I completely understand, it's been quite some time. We're trying to get on top of the old PRs, and it's probably better to follow up than to just let them sit longer.

**Comment by ariporad** [comment]
@nfischer, @idearat: bump.

**Comment by nfischer** [comment]
`grep -l` has been implemented and merged. I think `grep -s` isn't worth implementing, since it can be emulated with `config.silent = true; grep('-s' ...); config.silent = false;`. I'm going to close this for now, feel free to re-open if `-s` is important (or if `-l` support isn't quite right).

**Comment by idearat** [comment]
Seems reasonable.

**Pull request closed without merging**
