### PR TITLE
issue-407: Add regular files unit tests and fix symlink copy behavior

### PR DESCRIPTION
**Pull request by charlesverge**
Fix for #407 , includes test case for basic cp -L commands and additional cp -RL test case

### CODE REVIEW

**Comment by nfischer** [comment]
LGTM

**Comment by nfischer** [comment]
@charlesverge This looks perfect! Nice work.

**Comment by charlesverge** [comment]
@nfischer I added an additional commit to handle windows permissions, copied from test/ln.js

Also an additional check that the combo of -r and -L does not change behavior.

**Comment by nfischer** [comment]
LGTM

**Comment by nfischer** [comment]
@ariporad Feel free to merge if this looks good.

**Pull request merged**
