### PR TITLE
Fix symlinking on Windows

### LINKED ISSUE #301: `link -s` is broken for files on Windows
Currently we simply use `junction` as the linking method on Windows do avoid any linking permissions that Windows has (requires admin permissions to link a file). This though only works for directories so we need to check the source item type and use the proper link method accordingly.

### PR DESCRIPTION
**Pull request by BYK**
Fixes symlink creation on Windows systems and adds a test
for symlinking directories since it needs special treatment
on Windows.

Fixes #301.

### CODE REVIEW

**Comment by BYK** [comment]
Gonna fox POSIX issues.

**Comment by BYK** [comment]
Okay, should be fixed now.

**Comment by nfischer** [comment]
I haven't tested this on my windows machine, but it looks like it won't break linux/mac behavior, and it definitely looks like an improvement for Windows behavior. Since it passes all the CI, LGTM.

**Comment by BYK** [comment]
Rebased

**Comment by ariporad** [comment]
LGTM!

**Comment by ariporad** [comment]
Thanks @BYK!

**Pull request merged**
