### PR TITLE
Make sure Which() on Windows platform always return the command with …

### PR DESCRIPTION
**Pull request by TingluoHuang**
…extension.

### CODE REVIEW

**Comment by TingluoHuang** [comment]
For issue #238.

**Comment by mtscout6** [comment]
This looks reasonable to me @arturadib thoughts?

**Comment by arturadib** [comment]
:+1:

**Comment by nfischer** [comment]
It looks like the priority of `.bat`, `.cmd`, and `.exe` is not correct here.

I tested this on my Windows 7 64-bit machine as follows: I created files in my path named `test.bat`, `test.cmd`, and `test.exe`. Each file performs a simple print statement to help distinguish it from the other files. Here is what I saw:

```
> test # calls test.exe, not the others
this is exe
> del test.exe
> test # since there's no .exe, it calls .bat
this is bat
> del  test.bat
> test # since there's no .exe or .bat, it calls .cmd
this is cmd
```

So I think that `which()` should check for extensions in the order:

 1. `.exe`
 2. `.bat`
 3. `.cmd`

@TingluoHuang would you be able to add this to your PR? Aside from that, this looks ready to merge.

**Comment by TingluoHuang** [comment]
@nfischer 
attempt = baseAttempt + '.exe';
attempt = baseAttempt + '.cmd';
attempt = baseAttempt + '.bat';
The current priority in the code is already this one you want, isn't it?

**Comment by nfischer** [comment]
I believe that priority is `.exe`, `.cmd`, `.bat` (which is coincidentally reverse alphabetical order), and I believe the correct priority is `.exe`, `.bat`, `.cmd` (which is not reverse alphabetical order). Let me know if I'm missing something.

**Comment by nfischer** [comment]
@TingluoHuang can you verify that the priority is as I described? If so, and we get that fixed in the code, then I think this is good to merge.

**Comment by TingluoHuang** [comment]
@nfischer The priority you mentioned is correct, i update the PR.

**Comment by nfischer** [comment]
@TingluoHuang Can you rebase off master and squash your commits? I think this is safe to merge after that (if it passes the CI).

Once we get Windows CI running, we should probably add a specific test case for this, but we can do that later.

**Comment by nfischer** [comment]
LGTM. @arturadib @ariporad Feel free to merge

**Comment by ariporad** [comment]
:+1:

**Comment by BYK** [comment]
Windows has a PATHEXT environment variable that tells which files are "self executable". Instead of a fixed list of `.exe`, `.cmd` etc we should probably use that. Similar code in Python: https://github.com/scopatz/xonsh/blob/57e7c1f43879e6394342a17638f2a9b6cb80bc23/xonsh/built_ins.py#L284-L298

**Comment by BYK** [comment]
FYI I'm willing to submit a PR that does this if you agree :)

**Comment by nfischer** [comment]
@BYK would #134 be along the lines of what you're talking about? Perhaps we should ping that thread and see if that could get rebased off master.

I wasn't aware of the variable, but it seems like it's the right way to go. Thanks for bringing it to my attention!

**Comment by BYK** [comment]
@nfischer no problem :) Also reviewed the new patch!

**Pull request merged**
