### PR TITLE
Add newline to output of echo

### LINKED ISSUE #476: Echo doesn't return value ending in a trailing newline
### Node version:

v6.2.0
### ShellJS version (the most recent version/Github branch you see the bug on):

0.7.0
### Operating system:

OSX 10.11.5
### Description of the bug:

Using `toEnd` doesn't prepend a newline when chained to `echo`.
### Example ShellJS command to reproduce the error:

``` javascript
shell.echo(`A`).toEnd(`test.txt`);
shell.echo(`B`).toEnd(`test.txt`);
```

test.txt becomes: `AB`

``` bash
echo A >> test.txt
echo B >> test.txt
```

test.txt becomes:

```
A
B
```

### PR DESCRIPTION
**Pull request by freitagbr**
Fixes #476

### CODE REVIEW

**Comment by nfischer** [comment]
@freitagbr Can you also add a test?

**Comment by freitagbr** [comment]
@nfischer Sure. I am thinking however that the behavior of this should be changed. Currently, `console.log` is used, and a newline is automatically placed at the end of the output. Instead, I think `process.stdout.write` should be used, as it only writes to stdout what is literally passed in.

**Comment by nfischer** [comment]
@freitagbr unix `echo` adds a newline by default. Probably best to keep using `console.log()` for this scenario.

You raise a good point though, so I filed #557

**Comment by nfischer** [comment]
Looks good. Let's wait until we ava-ify the tests for `echo` though, to avoid callback hell.

**Comment by freitagbr** [comment]
Ok. Is it worth adding support for `-n` in the meantime? Or should I wait until this is merged?

**Comment by nfischer** [comment]
You can do that in a new PR, it shouldn't necessarily be blocked by this. Either way, let's wait to get the `echo` tests ava-ified.

**Comment by freitagbr** [comment]
@nfischer I rewrote the test for this branch.

**Comment by nfischer** [comment]
LGTM, make sure we land this on dev, not master.

**Pull request merged**
