### PR TITLE
handling symlink with '-L' option for copying

### PR DESCRIPTION
**Pull request by sparkleholic**
Related Issue & Code changes
* https://github.com/arturadib/shelljs/issues/69
* https://github.com/eisnerd/shelljs/commit/2e0ab9d9256e6b59ed128358eebc8b05d4bdd9d7

```
shelljs.cp('-r', src, dst);  // copy symbolic links as it is.
shelljs.cp('-rL', src, dst); // copy real files of symbolic link
```

### CODE REVIEW

**Comment by nfischer** [comment]
@sparkleholic would you be able to add tests? Sorry about the delay!

**Comment by ariporad** [comment]
@sparkleholic: Any chance you'd be able to add some tests?  Thanks!

**Comment by nfischer** [comment]
@ariporad this might be another PR we should take over, unless @sparkleholic responds soon.

**Comment by ariporad** [comment]
@nfischer: Works for me.

**Comment by nfischer** [comment]
@sparkleholic Thanks for the PR! I'm afraid I'll have to close this since we opted with #232 for `cp -L`.

**Pull request closed without merging**
