### PR TITLE
Bump GitHub workflow actions to latest versions

### PR DESCRIPTION
**Pull request by deining**
This PR bumps two GitHub workflow actions to their latest versions.

### CODE REVIEW

**Comment by deining** [comment]
I will sign my commit soon,

**Comment by deining** [comment]
The commit is signed now.

**Review by nfischer — APPROVED** [review]
LGTM. Do you want to send a similar PR for https://github.com/shelljs/shx?

**Comment by nfischer** [comment]
Can you please rebase on top of the latest `master` branch? I made some changes today to fix up the tester bots.

**Comment by deining** [comment]
> Do you want to send a similar PR for https://github.com/shelljs/shx?

Done.

**Pull request merged**
