### PR TITLE
fix(ls): properly handle symlinks without a trailing slash on macOS

### LINKED ISSUE #446: ls() not returning an Array
### Node version:

v6.2.0

### ShellJS version (the most recent version/Github branch you see the bug on):

0.7.0

### Operating system:

OSX 15.5.0

### Description of the bug:

`shelljs.ls()` returns an object containing results (files and folders as elements of the array) and a bunch of methods and no longer an Array (as it used to do until 0.7 and as described in [the docs](https://github.com/shelljs/shelljs#lsoptions-path_array) : 

> Returns array of files in the given path, or in current directory if no path provided.

### Example ShellJS command to reproduce the error:

```javascript
require('shelljs').ls('/')
```

### PR DESCRIPTION
**Pull request by ariporad**
This is a really cheap hack, but it works.

Fixes #446.

### CODE REVIEW

**Comment by ariporad** [comment]
Could someone with Windows clone this branch and tell me if `test/resources/ls2` exists, and if it's properly a symlink that points to `test/resources/ls`? I think that's why AppVeyor is failing.

**Comment by nfischer** [comment]
@ariporad This breaks compatibility with unix `ls` for regular files. Ex:

```javascript
> exec('ls file.txt');
file.txt
> ls('file.txt');
ls: no such file or directory: file.txt
```

This bug is not visible on the master branch of ShellJS.

We should probably add tests for `ls()` being called on regular files though (can't believe this wasn't already tested).

**Comment by ariporad** [comment]
Hmm...

Maybe we should just file a bug in node for this... It doesn't really seem like our problem

**Comment by nfischer** [comment]
Whether or not this is an issue we should address, it seems clear that this approach isn't the right way to address this.

@ariporad If you think this is a bug with node's core, feel free to file a report.

**Pull request closed without merging**
