### PR TITLE
Add Cash cross-reference

### PR DESCRIPTION
**Pull request by dthree**
As per:

https://github.com/dthree/cash/pull/24#

:)

### CODE REVIEW

**Comment by nfischer** [comment]
LGTM!

**Comment by ariporad** [comment]
@nfischer: What do you think? I feel like it would be better if we linked to the wiki in the README, or just move all the related projects to the README?

**Comment by nfischer** [comment]
I think we should like to our wiki in the README. I'm not opposed to linking to cash directly as well (after all, they link back to us).

**Comment by dthree** [comment]
It's totally up to you guys, whatever you want to do is fine with me. Just let me know what to change.

**Comment by ariporad** [comment]
Hmm...

I feel that if they're putting us in their README, we should do the same, so maybe we should just put all related projects in the README. (Plus, then it's version controlled and we have to approve changes).

**Comment by nfischer** [comment]
I say that we try it out as-is, and also add a link to our wiki (I can do that as a separate commit).

**Comment by nfischer** [comment]
I'm going to go ahead and merge this in. I may adjust things a bit in the README when I go through and update docs.

**Comment by dthree** [comment]
Thanks! :star2:

**Pull request merged**
