### PR TITLE
Fix: errors on working without permission 

### PR DESCRIPTION
**Pull request by HyperUa**

### CODE REVIEW

**Comment by nfischer** [comment]
Thanks for the PR! Would you be able to add tests for these cases? Tests are either in `test/` or `ava-test/`

**Comment by nfischer** [comment]
@HyperUa can you fix the lint errors?

**Comment by HyperUa** [comment]
@nfischer About testing: I can't make cross platform decision. 
I tried to work with files with other owner and got errors, that's why I added the code. In my opinion it is better to say that user doesn't have permission than throwing error.

**Comment by nfischer** [comment]
@HyperUa if you can't make a cross-platform test, can you at least make a unix-specific or windows-specific test? We haven't received any bugs about this, so I have no idea what this code is fixing. We have a general policy against merging untested code unless there's a good reason why it can't be tested.

**Comment by nfischer** [comment]
@HyperUa any follow up on my previous comments? It would be great if you could either add some tests or explain how I can reproduce the issues that this PR solves. Thanks.

**Comment by nfischer** [comment]
Closing this, due to lack of a response. If someone can show me the cases this code handles, I'll reopen and take a look.

**Pull request closed without merging**
