### PR TITLE
chore(gitter/travis): add gitter webhook to travis

### PR DESCRIPTION
**Pull request by ariporad**

### CODE REVIEW

**Comment by nfischer** [comment]
What are these webhooks for?

**Comment by ariporad** [comment]
@nfisher: they add travis build status to the gitter sidebar.

**Comment by nfischer** [comment]
LGTM

**Comment by nfischer** [comment]
@ariporad looks like there are just some merge conflicts (probably since I added some steps to the travis build)

**Comment by nfischer** [comment]
I rebased to resolve merge conflicts. I'll merge once this passes CI

**Comment by ariporad** [comment]
Ok, Travis passed, so I'm going to merge.

**Pull request merged**
