### PR TITLE
Don't do `console.log.apply(this, ...)`.

### LINKED ISSUE #255: console.log.apply throwing TypeError: Illegal Invocation
I am trying to test pdf.js in [iron-node](https://s-a.github.io/iron-node/) (Electron) and is getting the below error.

	TypeError: Illegal invocation
	    at _echo (/Users/anoopelias/Workspace/JavaScript/Mozilla/pdfjs/pdf.js/node_modules/shelljs/src/echo.js:17:15)
	    at Function.target.browsertest (/Users/anoopelias/Workspace/JavaScript/Mozilla/pdfjs/pdf.js/make.js:1214:3)
	    at Object.global.target.(anonymous function) [as browsertest] (/Users/anoopelias/Workspace/JavaScript/Mozilla/pdfjs/pdf.js/node_modules/shelljs/make.js:28:26)
	    at /Users/anoopelias/Workspace/JavaScript/Mozilla/pdfjs/pdf.js/node_modules/shelljs/make.js:38:27
	    at Array.forEach (native)
	    at /Users/anoopelias/Workspace/JavaScript/Mozilla/pdfjs/pdf.js/node_modules/shelljs/make.js:36:10

Dug through it and then reached [this line](https://github.com/shelljs/shelljs/blob/561b1ea99ce5bebde07bc70342a8d1cc59279ea0/src/echo.js#L17) in shelljs,

It seems this type of usage of `console.log.apply` may not work everywhere. See relevant StackOverflow [link](http://stackoverflow.com/questions/8159233/typeerror-illegal-invocation-on-console-log-apply).

One more occurrence of the same [here](https://github.com/shelljs/shelljs/blob/e5c26fdaa33ec5f87b55698d6bbb10bb0967eab5/src/common.js#L24),

### PR DESCRIPTION
**Pull request by ariporad**
Fixes #255.

### CODE REVIEW

**Comment by nfischer** [comment]
Could we re-ping this to trigger the CI?

**Comment by nfischer** [comment]
This looks good, but I'd like to verify that it passes the CI before merging. Perhaps we can rebase off master once #267 is merged (since the `log()` function uses `console.error` in that PR)?

Aside from that, I expect this to work on both Windows and *nix.

**Comment by nfischer** [comment]
@ariporad if the merge conflicts can be resolved, I can merge this :+1:

**Comment by ariporad** [comment]
@nfisher: there are none. Merging

**Comment by nfischer** [comment]
I think the only issue is that I changed a `console.log` to a `console.error`. Should be an easy fix.

**Comment by ariporad** [comment]
@nfischer: Fixed. [`git refork`](https://gist.github.com/ariporad/a067e59d8f07d69ccf9d) to the rescue!

**Comment by nfischer** [comment]
@ariporad Awesome! I'll merge.

**Pull request merged**
