### PR TITLE
docs(chmod): document `options` argument

### PR DESCRIPTION
**Pull request by gkalpak**

### CODE REVIEW

**Comment by freitagbr** [comment]
@gkalpak Thank you for the PR!

**Comment by gkalpak** [comment]
Done.

**Comment by freitagbr** [comment]
Awesome, thanks again.

**Comment by petebacondarwin** [comment]
@gkalpak and @freitagbr we also need to update the `@types/shelljs` typings file: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/shelljs/index.d.ts#L391

**Comment by gkalpak** [comment]
DefinitelyTyped/DefinitelyTyped#25332

**Pull request merged**
